<?php

namespace Ashishnimrot\Website\Providers;


use Illuminate\Support\ServiceProvider;

class WebsiteServiceProvider extends ServiceProvider
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    public function boot()
    {
        info("I am ashish.");
    }

}
